a = int(100000)
b = int(50000)
c = int(20000)
d = int(10000)
e = int(5000)
f = int(2000)
g = int(1000)
h = int(500)
i = int(200)
j = int(100)
k = int(50)
print ("PERCOBAAN PERTAMA ALGORITMA GREEDY /n")
n = int(input("Masukkan Nilai Anda :"))

x = int(n / a)
y = int(n - a * x)
z = int(y / b)
u = int(y - b)
t = int(u / c)
w = int(u - c)
v = int(w / d)
f = int(w - d)
g = int(w / d)

if n >= a:
    print(a ,"sbnyk", x)
    print(b, "sbnyak", z)
    print(c, "sbnyk" , t)
    print(d, "sbnyk" , v)
    print(e, "sbnyk" , g)